version: 2
jobs:
  build-and-deploy:
    docker:
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "javascript/package.json" }}
            - v1-dependencies-

      - run: cd javascript && yarn install

      - save_cache:
          paths:
            - javascript/node_modules
          key: v1-dependencies-{{ checksum "javascript/package.json" }}
      - run: cd javascript && yarn run prettier --check "src/**/*.js"
      # - run: cd javascript && yarn test
      - run: cd javascript && yarn build
      - run: mkdir deploy
      - deploy:
          name: Website deployement
          working_directory: ~/repo/deploy
          command: |
            git clone --depth 1 https://${GITHUB_TOKEN}@github.com/fabiencelier/fabiencelier.github.io.git .
            rm -rf *
            cp -r ../javascript/build/* .
            git config credential.helper 'cache --timeout=120'
            git config user.email "$EMAIL"
            git config user.name "$USERNAME"
            git add .
            git commit --allow-empty -m "[OUTLIVE] Deploy $CIRCLE_SHA1 from CI"
            # Push quietly to prevent showing the token in log
            git push -q https://${GITHUB_TOKEN}@github.com/fabiencelier/fabiencelier.github.io.git master

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: master
